# ./Brewfile

tap 'adoptopenjdk/openjdk'
tap 'cloudflare/cloudflare'
tap 'dotenvx/brew'

brew 'automake'
brew 'bat'
brew 'cloudflare/homebrew-cloudflare/curl'
brew 'coreutils'
brew 'deno'
brew 'difftastic'
brew 'docker-compose'
brew 'docker'
brew 'dotenvx/brew/dotenvx'
brew 'eza'
brew 'ffmpeg'
brew 'gh'
brew 'gibo'
brew 'git-delta'
brew 'git'
brew 'gnu-sed'
brew 'gnupg'
brew 'gnutls'
brew 'imagemagick'
brew 'iperf3'
brew 'jq'
brew 'lefthook'
brew 'libheif'
brew 'libraw'
brew 'mas'
brew 'peco'
brew 'stow'
brew 'switchaudio-osx'
brew 'tig'
brew 'tlrc'
brew 'tree'
brew 'zsh-autosuggestions'
brew 'zsh-completions'

cask 'discord'
cask 'font-monaspace'
cask 'font-plemol-jp-hs'
cask 'font-plemol-jp-nf'
cask 'font-plemol-jp'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-japanese-ime'
cask 'keeper-password-manager'
cask 'krisp'
# cask 'macx-dvd-ripper-pro'
cask 'microsoft-auto-update'
cask 'microsoft-edge'
cask 'raycast'
cask 'visual-studio-code'
cask 'zoom'

# mas 'AmorphousDiskMark', id: 1168254295
# mas 'Apple Configurator 2', id: 1037126344
# mas 'Compressor', id: 424390742
# mas 'Final Cut Pro', id: 424389933
# mas 'Keynote', id: 409183694
# mas 'LINE', id: 539883307
# mas 'Motion', id: 434290957
# mas 'Numbers', id: 409203825
# mas 'Pages', id: 409201541
# mas 'Slack', id: 803453959
# mas 'Xcode', id: 497799835

vscode 'aaron-bond.better-comments'
vscode 'alexcvzz.vscode-sqlite'
vscode 'astro-build.astro-vscode'
vscode 'beardedbear.beardedicons'
vscode 'beardedbear.beardedtheme'
vscode 'christian-kohler.path-intellisense'
vscode 'dbaeumer.vscode-eslint'
vscode 'denoland.vscode-deno'
vscode 'dsznajder.es7-react-js-snippets'
vscode 'eamodio.gitlens'
vscode 'editorconfig.editorconfig'
vscode 'enkia.tokyo-night'
vscode 'eriklynd.json-tools'
vscode 'esbenp.prettier-vscode'
vscode 'formulahendry.auto-close-tag'
vscode 'formulahendry.auto-rename-tag'
vscode 'foxundermoon.shell-format'
vscode 'github.copilot-chat'
vscode 'github.copilot'
vscode 'github.vscode-github-actions'
vscode 'github.vscode-pull-request-github'
vscode 'google.geminicodeassist'
vscode 'googlecloudtools.cloudcode'
vscode 'gruntfuggly.todo-tree'
vscode 'hookyqr.minify'
vscode 'ics.japanese-proofreading'
vscode 'idleberg.applescript'
vscode 'kirozen.wordcounter'
vscode 'mikestead.dotenv'
vscode 'ms-ceintl.vscode-language-pack-ja'
vscode 'ms-playwright.playwright'
vscode 'richie5um2.vscode-sort-json'
vscode 'saoudrizwan.claude-dev'
vscode 'steoates.autoimport'
vscode 'streetsidesoftware.code-spell-checker'
vscode 'stylelint.vscode-stylelint'
vscode 'tamasfe.even-better-toml'
vscode 'tomoki1207.pdf'
vscode 'vscode-icons-team.vscode-icons'
vscode 'xabikos.javascriptsnippets'
