#!/bin/sh

type brew >/dev/null 2>&1
if [ $? -ne 0 ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  eval $(/opt/homebrew/bin/brew shellenv)
fi

brew bundle -v --file=~/Workspaces/dotfiles/Brewfile

stow -R -v -d ~/Workspaces/dotfiles/packages -t ~ zsh ssh
stow -R -v -d ~/Workspaces/dotfiles/packages -t ~/Library/Application\ Support/Code/User code

cd $HOME

exec $SHELL -l
