min_version = { soft = "2026.7.4" }

[tools]
claude-code = "latest"
deno = "latest"
gemini = "latest"
node = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:rimraf" = "latest"
"npm:oxlint" = "latest"
"npm:oxfmt" = "latest"
pnpm = "latest"
"npm:greptile" = "latest"
"npm:@colbymchenry/codegraph" = "latest"
"npm:@playwright/mcp" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
plugin_autoupdate_last_check_duration = "10080" # 7 days
